name: mle-dev
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=1.0.0
  - alsa-lib=1.2.13
  - babel=2.16.0
  - black=24.10.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - cairo=1.18.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - docutils=0.21.2
  - double-conversion=3.3.0
  - expat=2.6.4
  - flake8=7.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagesize=1.4.1
  - isort=5.13.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.6
  - libclang13=19.1.6
  - libcups=2.3.3
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.6
  - liblzma=5.6.3
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.28
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=17.2
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mccabe=0.7.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - numpy=2.2.0
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pathspec=0.12.1
  - pcre2=10.44
  - pillow=11.0.0
  - pip=24.3.1
  - pixman=0.44.2
  - platformdirs=4.3.6
  - pthread-stubs=0.4
  - pycodestyle=2.12.1
  - pycparser=2.22
  - pyflakes=3.2.0
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyside6=6.8.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.10
  - pytz=2024.1
  - qhull=2020.2
  - qt6-main=6.8.1
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.6.0
  - scipy=1.14.1
  - setuptools=75.6.0
  - six=1.17.0
  - snowballstemmer=2.2.0
  - sphinx=8.1.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.4.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wayland=1.23.1
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - exceptiongroup==1.2.2
      - iniconfig==2.0.0
      - nonstandardcode==0.1
      - pluggy==1.5.0
      - pytest==8.3.4

# prefix: /home/suraj/miniforge3/envs/mle-dev
